name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    env:
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Lint
        run: |
          ruff --version
          ruff check .
      - name: Tests
        run: |
          pytest -q
      - name: CLI smoke
        run: |
          python -m ios_toolkit.cli --help
